# (C) Copyright 2026, SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

name: CI orchestrator

on:
  push:
    branches: [ master, 'release-*' ]
    tags: [ 'v*' ]
  pull_request:
  workflow_dispatch:

env:
  GLOBAL_PROJECT_FOLDER: "astarte-device-sdk-zephyr"
  GLOBAL_LIB_NAME: "astarte_device_sdk"
  GLOBAL_SAMPLE_NAME: "astarte_app"
  GLOBAL_DOCS_ORG: "astarte-platform"

jobs:
  run-unit-tests:
    name: Run the unit tests
    uses: ./.github/workflows/test.yml
    with:
      PROJECT_MANIFEST_FOLDER: ${{ env.GLOBAL_PROJECT_FOLDER }}
      LIBRARY_NAME: ${{ env.GLOBAL_LIB_NAME }}

  run-static-analysis:
    name: Run the static analysis
    uses: ./.github/workflows/static.yml
    with:
      PROJECT_MANIFEST_FOLDER: ${{ env.GLOBAL_PROJECT_FOLDER }}
      SAMPLE_NAME: ${{ env.GLOBAL_PROJECT_FOLDER }}

  run-build:
    name: Run build
    uses: ./.github/workflows/build.yml
    with:
      PROJECT_MANIFEST_FOLDER: ${{ env.GLOBAL_PROJECT_FOLDER }}
      SAMPLE_NAME: ${{ env.GLOBAL_PROJECT_FOLDER }}

  run-doc-generation:
    name: Run documentation generation
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release-')
    uses: ./.github/workflows/doc-generation.yml
    secrets: inherit
    with:
      PROJECT_MANIFEST_FOLDER: ${{ env.GLOBAL_PROJECT_FOLDER }}
      DOCS_REMOTE_ORG: ${{ env.GLOBAL_DOCS_ORG }}
      MACRO_PROJECT_BASE: "ASTARTE_DEVICE_SDK_BASE"
      REMOTE_PROJECT_FOLDER: "device-sdks"
      USER_EMAIL_API: "astarte-machine-sdk@ispirata.com"
      GET_STARTED_ROOT_REPO: "sdk-doc"
      USER_EMAIL_GET_STARTED: "astarte-machine@ispirata.com"

  run-doc-check:
    name: Run documentation check
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'pull_request'
    uses: ./.github/workflows/doc-check.yml
    with:
      PROJECT_MANIFEST_FOLDER: ${{ env.GLOBAL_PROJECT_FOLDER }}
      MACRO_PROJECT_BASE: "ASTARTE_DEVICE_SDK_BASE"
      MACRO_PROJECT_EXTENDED_DOCS: "ASTARTE_DEVICE_SDK_EXTENDED_DOCS"
